# Generated by Django 5.2 on 2025-04-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_producto", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("id_inventario", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField(default=0)),
                ("alert_threshold", models.IntegerField(default=2)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="sucursales.sucursal",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existencias",
                        to="inventory.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
            },
        ),
        migrations.CreateModel(
            name="TransaccionInventario",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("venta", "Venta"),
                            ("ajuste", "Ajuste"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=13,
                    ),
                ),
                ("transaccion_fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="inventory.producto",
                    ),
                ),
                (
                    "id_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="sucursales.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Inventario",
                "verbose_name_plural": "Transacciones de Inventario",
                "db_table": "inventario_transaccion",
            },
        ),
    ]
