# Generated by Django 5.2 on 2025-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="contrasena",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="email",
        ),
    ]
