# Generated by Django 5.2 on 2025-04-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta de crédito/débito"),
                            ("nequi", "Nequi"),
                            ("daviplata", "Daviplata"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "referencia_pago",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pago",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("entregado", "Entregado"),
                            ("pagado", "Pagado"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PedidoMesero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Pedido-Mesero",
                "verbose_name_plural": "Asignaciones Pedido-Mesero",
                "db_table": "pedido_mesero",
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id_detalle_pedido",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("descripcion", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedidos",
                "db_table": "detalle_pedido",
            },
        ),
    ]
